# Generated by Django 2.2.4 on 2019-08-16 01:31

from django.conf import settings
from django.db import migrations, models
import face_recog.models
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FaceData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo_id', models.ImageField(blank=True, null=True, upload_to='tmp/')),
                ('encoded', jsonfield.fields.JSONField()),
                ('user', models.ForeignKey(on_delete='models.CASCADE', related_name='face_data', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
