# Generated by Django 2.2.4 on 2019-08-16 02:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('face_recog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facedata',
            name='photo_id',
        ),
    ]
